# Generated by Django 5.0.1 on 2024-05-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("rate", models.FloatField()),
                ("overtime_pay", models.FloatField(blank=True, null=True)),
                ("allowance", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(default=0, max_length=30)),
                ("date_range", models.CharField(default=0, max_length=50)),
                ("year", models.CharField(default=0, max_length=4)),
                ("pay_cycle", models.IntegerField(default=0)),
                ("rate", models.FloatField(default=0)),
                ("earnings_allowance", models.FloatField(default=0)),
                ("deductions_tax", models.FloatField(default=0)),
                ("deductions_health", models.FloatField(default=0)),
                ("pag_ibig", models.FloatField(default=0)),
                ("sss", models.FloatField(default=0)),
                ("overtime", models.FloatField(default=0)),
                ("total_pay", models.FloatField(default=0)),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll_app.employee",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
    ]
