# Generated by Django 5.0.1 on 2024-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="philhealth",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="overtime_pay",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
