# Generated by Django 5.0.1 on 2024-05-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0002_payslip_philhealth_alter_employee_allowance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="overtime_hours",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
