# Generated by Django 5.0.1 on 2024-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0003_employee_overtime_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="year",
            field=models.IntegerField(default=0),
        ),
    ]
