# Generated by Django 5.0.1 on 2024-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0004_alter_payslip_month_alter_payslip_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="total_deductions",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="month",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="year",
            field=models.CharField(default=0, max_length=4),
        ),
    ]
