# Generated by Django 5.0.1 on 2024-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0005_payslip_total_deductions_alter_payslip_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="total_earnings",
            field=models.FloatField(default=0),
        ),
    ]
