# Generated by Django 5.0.1 on 2024-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0006_payslip_total_earnings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="philhealth",
        ),
        migrations.AlterField(
            model_name="payslip",
            name="deductions_health",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="deductions_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="earnings_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="overtime",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="pag_ibig",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="sss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
