# Generated by Django 5.0.1 on 2024-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0007_remove_payslip_philhealth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id_number",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
