# Generated by Django 5.0.1 on 2024-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0008_alter_employee_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="rate",
            field=models.PositiveIntegerField(),
        ),
    ]
