# Generated by Django 5.1.6 on 2025-02-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCatT',
            fields=[
                ('expense_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_cat_name', models.CharField(max_length=50)),
                ('category_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'expense_cat_t',
                'managed': False,
            },
        ),
    ]
