# Generated by Django 5.1.6 on 2025-02-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecatt',
            options={'managed': True},
        ),
    ]
