# Generated by Django 5.1.6 on 2025-02-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0002_alter_expensecatt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseT',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('expense_amount', models.JSONField()),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'expense_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItemT',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_item_name', models.CharField(max_length=100)),
                ('menu_item_price', models.JSONField()),
                ('menu_item_cost', models.JSONField()),
                ('menu_item_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menu_item_timestamp', models.DateTimeField()),
                ('item_availability_status', models.IntegerField()),
            ],
            options={
                'db_table': 'menu_item_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineT',
            fields=[
                ('order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.JSONField()),
            ],
            options={
                'db_table': 'order_line_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderT',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=20)),
                ('order_timestamp', models.DateTimeField()),
                ('reference_num', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'order_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserT',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=13)),
                ('user_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_t',
                'managed': False,
            },
        ),
    ]
