# Generated by Django 5.1.3 on 2025-03-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0003_expenset_menuitemt_orderlinet_ordert_usert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemt',
            options={'managed': True},
        ),
    ]
