# Generated by Django 5.1.3 on 2025-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0004_alter_menuitemt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemt',
            name='item_availability_status',
            field=models.IntegerField(choices=[(1, 'For Sale'), (0, 'Discontinued')], default=1),
        ),
        migrations.AlterField(
            model_name='menuitemt',
            name='menu_item_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemt',
            name='menu_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemt',
            name='menu_item_profit',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemt',
            name='menu_item_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
