# Generated by Django 5.1.3 on 2025-03-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0005_alter_menuitemt_item_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemt',
            options={'managed': False},
        ),
    ]
