# Generated by Django 5.1.3 on 2025-03-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaoTasty', '0007_alter_menuitemt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemt',
            options={'managed': True},
        ),
    ]
