# Generated by Django 5.1.3 on 2024-11-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msys30app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="ac_availability",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is air conditioning needed?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="desktop_availability",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is a desktop needed?", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="elevator_availability",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is an elevator needed?", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="mic_connector_availability",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is a microphone connector needed?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="projector_availability",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is a projector needed?", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="speaker_availability",
            field=models.BooleanField(
                blank=True, default=False, help_text="Are speakers needed?", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinput",
            name="tv_availability",
            field=models.BooleanField(
                blank=True, default=False, help_text="Is a TV needed?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="building",
            field=models.CharField(
                blank=True,
                help_text="Building name where the venue is located.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="capacity_needed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Enter the capacity needed for the venue.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="duration",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "30 minutes"),
                    (2, "1 hour"),
                    (3, "1 hour 30 minutes"),
                    (4, "2 hours"),
                    (5, "2 hours 30 minutes"),
                    (6, "3 hours"),
                    (7, "3 hours 30 minutes"),
                    (8, "4 hours"),
                ],
                help_text="Select the duration of the reservation in 30-minute increments.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="reservation_date",
            field=models.DateField(
                blank=True,
                help_text="Reservation date in YYYY-MM-DD format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="target_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08:00", "08:00"),
                    ("09:30", "09:30"),
                    ("11:00", "11:00"),
                    ("12:30", "12:30"),
                    ("14:00", "14:00"),
                    ("15:30", "15:30"),
                    ("17:00", "17:00"),
                    ("18:30", "18:30"),
                ],
                help_text="Select a start time for the reservation.",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="venue_name",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the venue for the reservation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="msys30app.venues",
            ),
        ),
    ]
