# Generated by Django 5.1.3 on 2024-11-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msys30app", "0002_userinput_ac_availability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="facility_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Classroom", "Classroom"),
                    ("Lecture Hall", "Lecture Hall"),
                    ("Lecture Room", "Lecture Room"),
                ],
                help_text="Select the facility type for the reservation.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venues",
            name="facility_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Any"),
                    ("Classroom", "Classroom"),
                    ("Lecture Hall", "Lecture Hall"),
                    ("Lecture Room", "Lecture Room"),
                ],
                help_text="Select a facility type (optional).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="building",
            field=models.CharField(
                blank=True,
                choices=[("Faura", "Faura")],
                help_text="Building name where the venue is located.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservations",
            name="venue_name",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a venue (optional).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="msys30app.venues",
            ),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="building",
            field=models.CharField(
                blank=True,
                choices=[("Faura", "Faura")],
                help_text="Building name where the venue is located.",
                max_length=100,
                null=True,
            ),
        ),
    ]
