# Generated by Django 5.1.3 on 2024-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msys30app", "0003_userinput_facility_type_venues_facility_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venues",
            name="building",
            field=models.CharField(
                blank=True,
                choices=[("Faura", "Faura")],
                help_text="Building name where the venue is located.",
                max_length=100,
                null=True,
            ),
        ),
    ]
