# Generated by Django 5.1.3 on 2024-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msys30app", "0004_venues_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="equipment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Projector", "Projector"),
                    ("TV", "TV"),
                    ("Speaker", "Speaker"),
                    ("Desktop", "Desktop"),
                    ("Mic", "Mic"),
                    ("AC", "AC"),
                ],
                default="",
                help_text="Select equipment needed for this venue.",
                max_length=255,
            ),
        ),
    ]
